# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: zavastorefront
metadata:
  template: zavastorefront@0.0.1-beta

services:
  web:
    project: ./src
    language: csharp
    host: appservice

infra:
  provider: bicep
  path: infra
  module: main

pipeline:
  provider: github
